services:
  web-app:
    build: .
    ports:
      - "80:5000" # server port always on 80 and app on 5000
    volumes:
      - ./data:/data # persistent DB
    restart: always
    command: python app.py

  
  scraper: 
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/New_York
    volumes:
      - ./data:/data
    restart: always
    command: python ./scraper/scrape.py
    depends_on:
      - web-app