DROP TABLE IF EXISTS wishlist;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE wishlist (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	url TEXT UNIQUE NOT NULL,
	name TEXT NOT NULL,
	price INTEGER NOT NULL DEFAULT 0,
	lastSeenDate TEXT,
	lastSeenTime TEXT,
	cleaned BOOLEAN NOT NULL DEFAULT 0 CHECK (cleaned IN (0, 1))
);
